# Generated by Django 3.2.8 on 2022-02-09 19:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='clients/%Y/%m/', verbose_name='Logo')),
                ('title', models.CharField(max_length=100, verbose_name='Client name')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='Website')),
                ('awards', models.CharField(blank=True, choices=[('50', 'Top-50'), ('100', 'Top-100'), ('500', 'Top-500'), ('none', 'None')], default='none', max_length=14, verbose_name='Awords')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='distributor/%Y/%m/', verbose_name='Logo')),
                ('title', models.CharField(max_length=100, verbose_name='Distributor name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='Website')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
            },
        ),
        migrations.CreateModel(
            name='IceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/LOGO_ZE.png', upload_to='ice_type_image/%Y/%m/', verbose_name='Main foto')),
                ('title', models.CharField(max_length=100, verbose_name='Название льда')),
                ('size', models.CharField(default='', max_length=100, verbose_name='Размер льда')),
                ('slug', models.SlugField()),
                ('box_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cubes_quantity', models.IntegerField(default=1, verbose_name='Количество льда в пачке')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ice type',
                'verbose_name_plural': 'Ice types',
            },
        ),
        migrations.CreateModel(
            name='IceTypeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/icetype_photo/%Y/%m/', verbose_name='Image')),
                ('icetype_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.icetype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/client_photo/%Y/%m/', verbose_name='Image')),
                ('client_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.clients')),
            ],
        ),
    ]
