# Generated by Django 3.2.8 on 2022-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220219_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='icetype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='icetype',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='icetype',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название льда'),
        ),
        migrations.AddField(
            model_name='icetype',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Название льда'),
        ),
        migrations.AddField(
            model_name='zebartools',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='zebartools',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='zebartools',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='zebartools',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
